# Generated by Django 5.2.3 on 2025-06-23 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updates_at', models.DateTimeField(auto_now=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, choices=[('Technology', 'Technology'), ('Economy', 'Economy'), ('Sports', 'Sports'), ('Health', 'Health'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Science', 'Science'), ('Art', 'Art'), ('Food', 'Food'), ('Travel', 'Travel'), ('Fashion', 'Fashion'), ('Business', 'Business'), ('Lifestyle', 'Lifestyle'), ('Other', 'Other')], max_length=255, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog_img')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
